Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,6 +39,13 @@ jobs:
       - name: 安装依赖
         run: npm install
         if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
+      - uses: actions/cache@v4
+        id: node-modules-cache
+        with:
+         path: node_modules
+         key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }} # 确保包含 package-lock.json
+      - name: Debug - Check modules
+        run: ls -la node_modules | grep crypto-js || echo "crypto-js not found!"
       - name: 签到
         run: npm run main
         env:
